# Generated by Django 5.2.4 on 2025-08-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
