# Generated by Django 5.2.4 on 2025-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0006_alter_customusermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
