# Generated by Django 5.2.4 on 2025-08-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_customusermodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
